# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mywindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.
#!/usr/bin/env python
# -*- encoding: utf-8 -*-
#!/usr/bin/env python

# -*- encoding: utf-8 -*-
'''
@File          :   MyWindos.py
@Function Name :   main
@Summary       :   程序入口main函数
@Parameters    :   /
@Return        :   /
@Time          :   2022/04/11 14:22:18
@Author        :   BatterMain
@Version       :   1.0
'''

from multiprocessing.connection import wait
from time import sleep, time
from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtCore import *
from PyQt5.QtGui import *
from PyQt5.QtWidgets import *
import sys
import TextAPI
from builtins import str
import BingDwenDwen
class Ui_Dialog(QtWidgets.QWidget):
    def setupUi(self, Dialog):
        
        Dialog.setObjectName("Dialog")
        Dialog.resize(1179, 750)
        self.pushButton = QtWidgets.QPushButton(Dialog)
        self.pushButton.setGeometry(QtCore.QRect(300, 112, 551, 42))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        font.setKerning(True)
        self.pushButton.setFont(font)
        self.pushButton.setObjectName("pushButton")
        

        self.pushButton1 = QtWidgets.QPushButton(Dialog)
        self.pushButton1.setGeometry(QtCore.QRect(970, 28, 150, 39))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        font.setKerning(True)
        self.pushButton1.setFont(font)
        self.pushButton1.setObjectName("pushButton1")

        self.pushButton2 = QtWidgets.QPushButton(Dialog)
        self.pushButton2.setGeometry(QtCore.QRect(970, 67, 150, 39))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        font.setKerning(True)
        self.pushButton2.setFont(font)
        self.pushButton2.setObjectName("pushButton2")

        self.textBrowser = QtWidgets.QTextBrowser(Dialog)
        self.textBrowser.setGeometry(QtCore.QRect(5, 445, 1170, 300))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.textBrowser.setFont(font)
        self.textBrowser.setObjectName("textBrowser")
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(90, 30, 132, 33))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setGeometry(QtCore.QRect(90, 70, 132, 33))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")

        #加载图片控件
        
        self.labe3 = QtWidgets.QLabel(Dialog)
        self.labe3.setGeometry(QtCore.QRect(5, 163, 1170, 280))
        self.labe3.setStyleSheet("border: 3px solid #c8cdd7") 
        font = QtGui.QFont()
        font.setPointSize(20)
        self.labe3.setFont(font)
        self.labe3.setObjectName("labe3")
        self.labe3.setScaledContents(True)
        

        self.lineEdit = QtWidgets.QLineEdit(Dialog)
        self.lineEdit.setGeometry(QtCore.QRect(230, 25, 721, 39))
        font = QtGui.QFont()
        font.setPointSize(17)
        self.lineEdit.setFont(font)
        self.lineEdit.setObjectName("lineEdit")
        self.lineEdit_2 = QtWidgets.QLineEdit(Dialog)
        self.lineEdit_2.setGeometry(QtCore.QRect(230, 65, 721, 39))
        font = QtGui.QFont()
        font.setPointSize(17)
        self.lineEdit_2.setFont(font)
        self.lineEdit_2.setObjectName("lineEdit_2")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

        #按钮信号槽
        self.pushButton.clicked.connect(self.cofig_click)
        self.pushButton1.clicked.connect(self.msg)
        
        self.pushButton2.clicked.connect(self.msg1)

        #布局
        '''hbox = QHBoxLayout()
        hbox.addStretch()
        hbox.addWidget(self.label)
        hbox.addWidget(self.label_2)
        #hbox.addWidget(self.labe3)
        hbox.addWidget(self.lineEdit)
        hbox.addWidget(self.lineEdit_2)
        hbox.addWidget(self.pushButton)
        hbox.addWidget(self.pushButton1)
        hbox.addWidget(self.labe3)
        hbox.addWidget(self.textBrowser)'''

        #self.setLayout(hbox)
    def msg1(self):
        TextAPI.Love()
        BingDwenDwen.PythonBingDwenDwen()
        

    def msg(self):
        #directory1 = QFileDialog.getExistingDirectory(self,"选取文件夹","./")   #起始路径
        #print(directory1)
    
        fileName1, filetype = QtWidgets.QFileDialog.getOpenFileName(self,"选取文件","./", "All Files (*);;Excel Files (*.xls)")  #设置文件扩展名过滤,注意用双分号间隔
        print("文件路径："+fileName1)
        All_path = fileName1.replace('/',"\\")
        print('----->>>>>>---->>>>>>>>----->>>>>>----->>>>>>----->>>>>>' + All_path)
        self.lineEdit.setText(All_path)
        #return fileName1
        #files, ok1 = QFileDialog.getOpenFileNames(self,"多文件选择", "./", "All Files (*);;Text Files (*.txt)")
        #print(files,ok1)
    
        #fileName2, ok2 = QFileDialog.getSaveFileName(self,"文件保存", "./","All Files (*);;Text Files (*.txt)")
        pix = QPixmap(All_path)
        self.labe3.setPixmap(pix)
    def cofig_click(self):
        print("**************************************************************************************")
        print('检测路径：' + self.lineEdit.text())
        print("**************************************************************************************")
        print(TextAPI.textapi(self.lineEdit.text()))
        #self.lineEdit_2.setText(TextAPI.textapi(self.lineEdit.text()))
        self.lineEdit_2.setText("检测结果：你就是憨蛋！！不要狡辩！！哒咩哒咩哒咩吆！！")
        self.textBrowser.setText(TextAPI.textapi(self.lineEdit.text()))

        

        
    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "BetterMain-通用文本检测V1.0"))
        self.pushButton.setText(_translate("Dialog", "开  始  检  测"))
        self.pushButton1.setText(_translate("Dialog", "BetterMain"))
        self.pushButton2.setText(_translate("Dialog", "点我有惊喜！"))
        self.textBrowser.setHtml(_translate("Dialog", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'SimSun\'; font-size:20pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">检测中....</p></body></html>"))
        self.label.setText(_translate("Dialog", "图像路径"))
        self.label_2.setText(_translate("Dialog", "检测结果"))
        self.labe3.setText(_translate("Dialog", "                             检测图片"))

#启动界
def show_Mywindow():
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui =Ui_Dialog()
    ui.setupUi(MainWindow)
    
    MainWindow.show()
    
    sys.exit(app.exec_())
    

if __name__ == '__main__':
    show_Mywindow()
    
    
